# Generated by Django 4.2 on 2024-04-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image_url',
            field=models.CharField(blank=True, default='null', max_length=256, null=True),
        ),
    ]
