# Generated by Django 4.2 on 2024-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selers', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image_url',
            field=models.CharField(blank=True, default='https://i.imgur.com/XKAFJmx.png', max_length=256, null=True),
        ),
    ]
