# Generated by Django 4.2 on 2024-04-25 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selers', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Data',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 4, 25, 9, 11, 51, 939859), max_length=256, null=True),
        ),
    ]
