# Generated by Django 4.2 on 2024-04-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selers', '0004_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Data',
        ),
    ]
